### ISSUE TITLE
Need to adapt this a little

### ISSUE THREAD

**Issue by hhirsch** [gpichot/generator-cpp-suite#1]
Hello,
I have cloned this to https://github.com/GlPortal/yo-glportal because there is a lot I have to change so it fits my projects stack and coding style. Tell me if I should credit you more prominently.

**Comment by gpichot** [comment]
Hi Henry,

I am not looking for credit for this project (but that's okay if you put a reference to this project). I do not have the sufficient experience to tell wether or not this project is generating a standard C++ project structure and I am open to discussions for improvements.

Actually, I created this project because I wanted to have an efficient way to deploy a "basic" structure for my C++ projects involving good practices (automated testing, code coverage and so on). I have not finished it for now. As I stated in the README I still need to add features like CppCheck and Valgrind which could be useful. But that is a matter of personal interest and taste, that is why I am open to suggestions.

**Comment by hhirsch** [comment]
Yeah I wish there was a way we could make it configurable to fit either style but I think that is not the idea behind yo. If only the day had more hours. I would code the heck out of this.

P.S.: I am realy thankful that you have provided this. I have been looking for a good way to save me from typing the same stuff over and over again for a long time. Even though I am an emacs user this seems to me like a much more portable way to do it.

**Comment by gpichot** [comment]
You are welcome. I added support for micro benchmarking using Google Benchmark.
